namespace WowPacketParser.Enums.Version.V3_1_0_9767
{
    // ReSharper disable InconsistentNaming
    // 3.1.0
    public enum ObjectField
    {
        OBJECT_FIELD_GUID                                = 0x0,                // 0x000 - Size: 2 - Type: GUID - Flags: PUBLIC
        OBJECT_FIELD_TYPE                                = 0x2,                // 0x002 - Size: 1 - Type: INT - Flags: PUBLIC
        OBJECT_FIELD_ENTRY                               = 0x3,                // 0x003 - Size: 1 - Type: INT - Flags: PUBLIC
        OBJECT_FIELD_SCALE_X                             = 0x4,                // 0x004 - Size: 1 - Type: FLOAT - Flags: PUBLIC
        OBJECT_FIELD_PADDING                             = 0x5,                // 0x005 - Size: 1 - Type: INT - Flags: NONE
        OBJECT_END                                       = 0x6
    }

    public enum ContainerField
    {
        CONTAINER_FIELD_NUM_SLOTS                        = ItemField.ITEM_END + 0x0,     // 0x040 - Size: 1 - Type: INT - Flags: PUBLIC
        CONTAINER_ALIGN_PAD                              = ItemField.ITEM_END + 0x1,     // 0x041 - Size: 1 - Type: BYTES - Flags: NONE
        CONTAINER_FIELD_SLOT_1                           = ItemField.ITEM_END + 0x2,     // 0x042 - Size: 72 - Type: GUID - Flags: PUBLIC
        CONTAINER_END                                    = ItemField.ITEM_END + 0x4A     // 0x08A
    }

    public enum ItemField
    {
        ITEM_FIELD_OWNER                                 = ObjectField.OBJECT_END + 0x0,   // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
        ITEM_FIELD_CONTAINED                             = ObjectField.OBJECT_END + 0x2,   // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
        ITEM_FIELD_CREATOR                               = ObjectField.OBJECT_END + 0x4,   // 0x00A - Size: 2 - Type: GUID - Flags: PUBLIC
        ITEM_FIELD_GIFTCREATOR                           = ObjectField.OBJECT_END + 0x6,   // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
        ITEM_FIELD_STACK_COUNT                           = ObjectField.OBJECT_END + 0x8,   // 0x00E - Size: 1 - Type: INT - Flags: OWNER_ONLY + ITEM_OWNER
        ITEM_FIELD_DURATION                              = ObjectField.OBJECT_END + 0x9,   // 0x00F - Size: 1 - Type: INT - Flags: OWNER_ONLY + ITEM_OWNER
        ITEM_FIELD_SPELL_CHARGES                         = ObjectField.OBJECT_END + 0xA,   // 0x010 - Size: 5 - Type: INT - Flags: OWNER_ONLY + ITEM_OWNER
        ITEM_FIELD_FLAGS                                 = ObjectField.OBJECT_END + 0xF,   // 0x015 - Size: 1 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_1_1                       = ObjectField.OBJECT_END + 0x10,  // 0x016 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_1_3                       = ObjectField.OBJECT_END + 0x12,  // 0x018 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_2_1                       = ObjectField.OBJECT_END + 0x13,  // 0x019 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_2_3                       = ObjectField.OBJECT_END + 0x15,  // 0x01B - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_3_1                       = ObjectField.OBJECT_END + 0x16,  // 0x01C - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_3_3                       = ObjectField.OBJECT_END + 0x18,  // 0x01E - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_4_1                       = ObjectField.OBJECT_END + 0x19,  // 0x01F - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_4_3                       = ObjectField.OBJECT_END + 0x1B,  // 0x021 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_5_1                       = ObjectField.OBJECT_END + 0x1C,  // 0x022 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_5_3                       = ObjectField.OBJECT_END + 0x1E,  // 0x024 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_6_1                       = ObjectField.OBJECT_END + 0x1F,  // 0x025 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_6_3                       = ObjectField.OBJECT_END + 0x21,  // 0x027 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_7_1                       = ObjectField.OBJECT_END + 0x22,  // 0x028 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_7_3                       = ObjectField.OBJECT_END + 0x24,  // 0x02A - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_8_1                       = ObjectField.OBJECT_END + 0x25,  // 0x02B - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_8_3                       = ObjectField.OBJECT_END + 0x27,  // 0x02D - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_9_1                       = ObjectField.OBJECT_END + 0x28,  // 0x02E - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_9_3                       = ObjectField.OBJECT_END + 0x2A,  // 0x030 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_10_1                      = ObjectField.OBJECT_END + 0x2B,  // 0x031 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_10_3                      = ObjectField.OBJECT_END + 0x2D,  // 0x033 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_11_1                      = ObjectField.OBJECT_END + 0x2E,  // 0x034 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_11_3                      = ObjectField.OBJECT_END + 0x30,  // 0x036 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_12_1                      = ObjectField.OBJECT_END + 0x31,  // 0x037 - Size: 2 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_12_3                      = ObjectField.OBJECT_END + 0x33,  // 0x039 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        ITEM_FIELD_PROPERTY_SEED                         = ObjectField.OBJECT_END + 0x34,  // 0x03A - Size: 1 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_RANDOM_PROPERTIES_ID                  = ObjectField.OBJECT_END + 0x35,  // 0x03B - Size: 1 - Type: INT - Flags: PUBLIC
        ITEM_FIELD_ITEM_TEXT_ID                          = ObjectField.OBJECT_END + 0x36,  // 0x03C - Size: 1 - Type: INT - Flags: OWNER_ONLY
        ITEM_FIELD_DURABILITY                            = ObjectField.OBJECT_END + 0x37,  // 0x03D - Size: 1 - Type: INT - Flags: OWNER_ONLY + ITEM_OWNER
        ITEM_FIELD_MAXDURABILITY                         = ObjectField.OBJECT_END + 0x38,  // 0x03E - Size: 1 - Type: INT - Flags: OWNER_ONLY + ITEM_OWNER
        ITEM_FIELD_PAD                                   = ObjectField.OBJECT_END + 0x39,  // 0x03F - Size: 1 - Type: INT - Flags: NONE
        ITEM_END                                         = ObjectField.OBJECT_END + 0x3A   // 0x040
    }

    public enum UnitField
    {
        UNIT_FIELD_CHARM                                 = ObjectField.OBJECT_END + 0x0,   // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_SUMMON                                = ObjectField.OBJECT_END + 0x2,   // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_CRITTER                               = ObjectField.OBJECT_END + 0x4,   // 0x00A - Size: 2 - Type: GUID - Flags: PRIVATE
        UNIT_FIELD_CHARMEDBY                             = ObjectField.OBJECT_END + 0x6,   // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_SUMMONEDBY                            = ObjectField.OBJECT_END + 0x8,   // 0x00E - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_CREATEDBY                             = ObjectField.OBJECT_END + 0xA,   // 0x010 - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_TARGET                                = ObjectField.OBJECT_END + 0xC,   // 0x012 - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_CHANNEL_OBJECT                        = ObjectField.OBJECT_END + 0xE,   // 0x014 - Size: 2 - Type: GUID - Flags: PUBLIC
        UNIT_FIELD_BYTES_0                               = ObjectField.OBJECT_END + 0x10,  // 0x016 - Size: 1 - Type: BYTES - Flags: PUBLIC
        UNIT_FIELD_HEALTH                                = ObjectField.OBJECT_END + 0x11,  // 0x017 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER1                                = ObjectField.OBJECT_END + 0x12,  // 0x018 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER2                                = ObjectField.OBJECT_END + 0x13,  // 0x019 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER3                                = ObjectField.OBJECT_END + 0x14,  // 0x01A - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER4                                = ObjectField.OBJECT_END + 0x15,  // 0x01B - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER5                                = ObjectField.OBJECT_END + 0x16,  // 0x01C - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER6                                = ObjectField.OBJECT_END + 0x17,  // 0x01D - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER7                                = ObjectField.OBJECT_END + 0x18,  // 0x01E - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXHEALTH                             = ObjectField.OBJECT_END + 0x19,  // 0x01F - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER1                             = ObjectField.OBJECT_END + 0x1A,  // 0x020 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER2                             = ObjectField.OBJECT_END + 0x1B,  // 0x021 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER3                             = ObjectField.OBJECT_END + 0x1C,  // 0x022 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER4                             = ObjectField.OBJECT_END + 0x1D,  // 0x023 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER5                             = ObjectField.OBJECT_END + 0x1E,  // 0x024 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER6                             = ObjectField.OBJECT_END + 0x1F,  // 0x025 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MAXPOWER7                             = ObjectField.OBJECT_END + 0x20,  // 0x026 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER             = ObjectField.OBJECT_END + 0x21,  // 0x027 - Size: 7 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = ObjectField.OBJECT_END + 0x28,  // 0x02E - Size: 7 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_LEVEL                                 = ObjectField.OBJECT_END + 0x2F,  // 0x035 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_FACTIONTEMPLATE                       = ObjectField.OBJECT_END + 0x30,  // 0x036 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_VIRTUAL_ITEM_SLOT_ID                        = ObjectField.OBJECT_END + 0x31,  // 0x037 - Size: 3 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_FLAGS                                 = ObjectField.OBJECT_END + 0x34,  // 0x03A - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_FLAGS_2                               = ObjectField.OBJECT_END + 0x35,  // 0x03B - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_AURASTATE                             = ObjectField.OBJECT_END + 0x36,  // 0x03C - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_BASEATTACKTIME                        = ObjectField.OBJECT_END + 0x37,  // 0x03D - Size: 2 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_RANGEDATTACKTIME                      = ObjectField.OBJECT_END + 0x39,  // 0x03F - Size: 1 - Type: INT - Flags: PRIVATE
        UNIT_FIELD_BOUNDINGRADIUS                        = ObjectField.OBJECT_END + 0x3A,  // 0x040 - Size: 1 - Type: FLOAT - Flags: PUBLIC
        UNIT_FIELD_COMBATREACH                           = ObjectField.OBJECT_END + 0x3B,  // 0x041 - Size: 1 - Type: FLOAT - Flags: PUBLIC
        UNIT_FIELD_DISPLAYID                             = ObjectField.OBJECT_END + 0x3C,  // 0x042 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_NATIVEDISPLAYID                       = ObjectField.OBJECT_END + 0x3D,  // 0x043 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MOUNTDISPLAYID                        = ObjectField.OBJECT_END + 0x3E,  // 0x044 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_MINDAMAGE                             = ObjectField.OBJECT_END + 0x3F,  // 0x045 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + SPECIAL_INFO
        UNIT_FIELD_MAXDAMAGE                             = ObjectField.OBJECT_END + 0x40,  // 0x046 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + SPECIAL_INFO
        UNIT_FIELD_MINOFFHANDDAMAGE                      = ObjectField.OBJECT_END + 0x41,  // 0x047 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + SPECIAL_INFO
        UNIT_FIELD_MAXOFFHANDDAMAGE                      = ObjectField.OBJECT_END + 0x42,  // 0x048 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + SPECIAL_INFO
        UNIT_FIELD_BYTES_1                               = ObjectField.OBJECT_END + 0x43,  // 0x049 - Size: 1 - Type: BYTES - Flags: PUBLIC
        UNIT_FIELD_PETNUMBER                             = ObjectField.OBJECT_END + 0x44,  // 0x04A - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_PET_NAME_TIMESTAMP                    = ObjectField.OBJECT_END + 0x45,  // 0x04B - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_PETEXPERIENCE                         = ObjectField.OBJECT_END + 0x46,  // 0x04C - Size: 1 - Type: INT - Flags: OWNER_ONLY
        UNIT_FIELD_PETNEXTLEVELEXP                       = ObjectField.OBJECT_END + 0x47,  // 0x04D - Size: 1 - Type: INT - Flags: OWNER_ONLY
        UNIT_DYNAMIC_FLAGS                               = ObjectField.OBJECT_END + 0x48,  // 0x04E - Size: 1 - Type: INT - Flags: DYNAMIC
        UNIT_CHANNEL_SPELL                               = ObjectField.OBJECT_END + 0x49,  // 0x04F - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_MOD_CAST_SPEED                              = ObjectField.OBJECT_END + 0x4A,  // 0x050 - Size: 1 - Type: FLOAT - Flags: PUBLIC
        UNIT_CREATED_BY_SPELL                            = ObjectField.OBJECT_END + 0x4B,  // 0x051 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_NPC_FLAGS                                   = ObjectField.OBJECT_END + 0x4C,  // 0x052 - Size: 1 - Type: INT - Flags: DYNAMIC
        UNIT_NPC_EMOTESTATE                              = ObjectField.OBJECT_END + 0x4D,  // 0x053 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_STAT0                                 = ObjectField.OBJECT_END + 0x4E,  // 0x054 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_STAT1                                 = ObjectField.OBJECT_END + 0x4F,  // 0x055 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_STAT2                                 = ObjectField.OBJECT_END + 0x50,  // 0x056 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_STAT3                                 = ObjectField.OBJECT_END + 0x51,  // 0x057 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_STAT4                                 = ObjectField.OBJECT_END + 0x52,  // 0x058 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POSSTAT0                              = ObjectField.OBJECT_END + 0x53,  // 0x059 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POSSTAT1                              = ObjectField.OBJECT_END + 0x54,  // 0x05A - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POSSTAT2                              = ObjectField.OBJECT_END + 0x55,  // 0x05B - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POSSTAT3                              = ObjectField.OBJECT_END + 0x56,  // 0x05C - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POSSTAT4                              = ObjectField.OBJECT_END + 0x57,  // 0x05D - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_NEGSTAT0                              = ObjectField.OBJECT_END + 0x58,  // 0x05E - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_NEGSTAT1                              = ObjectField.OBJECT_END + 0x59,  // 0x05F - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_NEGSTAT2                              = ObjectField.OBJECT_END + 0x5A,  // 0x060 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_NEGSTAT3                              = ObjectField.OBJECT_END + 0x5B,  // 0x061 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_NEGSTAT4                              = ObjectField.OBJECT_END + 0x5C,  // 0x062 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_RESISTANCES                           = ObjectField.OBJECT_END + 0x5D,  // 0x063 - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY + SPECIAL_INFO
        UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE            = ObjectField.OBJECT_END + 0x64,  // 0x06A - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE            = ObjectField.OBJECT_END + 0x6B,  // 0x071 - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_BASE_MANA                             = ObjectField.OBJECT_END + 0x72,  // 0x078 - Size: 1 - Type: INT - Flags: PUBLIC
        UNIT_FIELD_BASE_HEALTH                           = ObjectField.OBJECT_END + 0x73,  // 0x079 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_BYTES_2                               = ObjectField.OBJECT_END + 0x74,  // 0x07A - Size: 1 - Type: BYTES - Flags: PUBLIC
        UNIT_FIELD_ATTACK_POWER                          = ObjectField.OBJECT_END + 0x75,  // 0x07B - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_ATTACK_POWER_MODS                     = ObjectField.OBJECT_END + 0x76,  // 0x07C - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_ATTACK_POWER_MULTIPLIER               = ObjectField.OBJECT_END + 0x77,  // 0x07D - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_RANGED_ATTACK_POWER                   = ObjectField.OBJECT_END + 0x78,  // 0x07E - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_RANGED_ATTACK_POWER_MODS              = ObjectField.OBJECT_END + 0x79,  // 0x07F - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER        = ObjectField.OBJECT_END + 0x7A,  // 0x080 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_MINRANGEDDAMAGE                       = ObjectField.OBJECT_END + 0x7B,  // 0x081 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_MAXRANGEDDAMAGE                       = ObjectField.OBJECT_END + 0x7C,  // 0x082 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POWER_COST_MODIFIER                   = ObjectField.OBJECT_END + 0x7D,  // 0x083 - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_POWER_COST_MULTIPLIER                 = ObjectField.OBJECT_END + 0x84,  // 0x08A - Size: 7 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_MAXHEALTHMODIFIER                     = ObjectField.OBJECT_END + 0x8B,  // 0x091 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
        UNIT_FIELD_HOVERHEIGHT                           = ObjectField.OBJECT_END + 0x8C,  // 0x092 - Size: 1 - Type: FLOAT - Flags: PUBLIC
        UNIT_FIELD_PADDING                               = ObjectField.OBJECT_END + 0x8D,  // 0x093 - Size: 1 - Type: INT - Flags: NONE
        UNIT_END                                         = ObjectField.OBJECT_END + 0x8E   // 0x094
    }

    public enum PlayerField
    {
        PLAYER_DUEL_ARBITER                              = UnitField.UNIT_END + 0x0,     // 0x094 - Size: 2 - Type: GUID - Flags: PUBLIC
        PLAYER_FLAGS                                     = UnitField.UNIT_END + 0x2,     // 0x096 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_GUILDID                                   = UnitField.UNIT_END + 0x3,     // 0x097 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_GUILDRANK                                 = UnitField.UNIT_END + 0x4,     // 0x098 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_BYTES                                     = UnitField.UNIT_END + 0x5,     // 0x099 - Size: 1 - Type: BYTES - Flags: PUBLIC
        PLAYER_BYTES_2                                   = UnitField.UNIT_END + 0x6,     // 0x09A - Size: 1 - Type: BYTES - Flags: PUBLIC
        PLAYER_BYTES_3                                   = UnitField.UNIT_END + 0x7,     // 0x09B - Size: 1 - Type: BYTES - Flags: PUBLIC
        PLAYER_DUEL_TEAM                                 = UnitField.UNIT_END + 0x8,     // 0x09C - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_GUILD_TIMESTAMP                           = UnitField.UNIT_END + 0x9,     // 0x09D - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_QUEST_LOG_1_1                             = UnitField.UNIT_END + 0xA,     // 0x09E - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_1_2                             = UnitField.UNIT_END + 0xB,     // 0x09F - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_1_3                             = UnitField.UNIT_END + 0xC,     // 0x0A0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_1_4                             = UnitField.UNIT_END + 0xD,     // 0x0A1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_2_1                             = UnitField.UNIT_END + 0xE,     // 0x0A2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_2_2                             = UnitField.UNIT_END + 0xF,     // 0x0A3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_2_3                             = UnitField.UNIT_END + 0x10,    // 0x0A4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_2_4                             = UnitField.UNIT_END + 0x11,    // 0x0A5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_3_1                             = UnitField.UNIT_END + 0x12,    // 0x0A6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_3_2                             = UnitField.UNIT_END + 0x13,    // 0x0A7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_3_3                             = UnitField.UNIT_END + 0x14,    // 0x0A8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_3_4                             = UnitField.UNIT_END + 0x15,    // 0x0A9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_4_1                             = UnitField.UNIT_END + 0x16,    // 0x0AA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_4_2                             = UnitField.UNIT_END + 0x17,    // 0x0AB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_4_3                             = UnitField.UNIT_END + 0x18,    // 0x0AC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_4_4                             = UnitField.UNIT_END + 0x19,    // 0x0AD - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_5_1                             = UnitField.UNIT_END + 0x1A,    // 0x0AE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_5_2                             = UnitField.UNIT_END + 0x1B,    // 0x0AF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_5_3                             = UnitField.UNIT_END + 0x1C,    // 0x0B0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_5_4                             = UnitField.UNIT_END + 0x1D,    // 0x0B1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_6_1                             = UnitField.UNIT_END + 0x1E,    // 0x0B2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_6_2                             = UnitField.UNIT_END + 0x1F,    // 0x0B3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_6_3                             = UnitField.UNIT_END + 0x20,    // 0x0B4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_6_4                             = UnitField.UNIT_END + 0x21,    // 0x0B5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_7_1                             = UnitField.UNIT_END + 0x22,    // 0x0B6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_7_2                             = UnitField.UNIT_END + 0x23,    // 0x0B7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_7_3                             = UnitField.UNIT_END + 0x24,    // 0x0B8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_7_4                             = UnitField.UNIT_END + 0x25,    // 0x0B9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_8_1                             = UnitField.UNIT_END + 0x26,    // 0x0BA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_8_2                             = UnitField.UNIT_END + 0x27,    // 0x0BB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_8_3                             = UnitField.UNIT_END + 0x28,    // 0x0BC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_8_4                             = UnitField.UNIT_END + 0x29,    // 0x0BD - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_9_1                             = UnitField.UNIT_END + 0x2A,    // 0x0BE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_9_2                             = UnitField.UNIT_END + 0x2B,    // 0x0BF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_9_3                             = UnitField.UNIT_END + 0x2C,    // 0x0C0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_9_4                             = UnitField.UNIT_END + 0x2D,    // 0x0C1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_10_1                            = UnitField.UNIT_END + 0x2E,    // 0x0C2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_10_2                            = UnitField.UNIT_END + 0x2F,    // 0x0C3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_10_3                            = UnitField.UNIT_END + 0x30,    // 0x0C4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_10_4                            = UnitField.UNIT_END + 0x31,    // 0x0C5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_11_1                            = UnitField.UNIT_END + 0x32,    // 0x0C6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_11_2                            = UnitField.UNIT_END + 0x33,    // 0x0C7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_11_3                            = UnitField.UNIT_END + 0x34,    // 0x0C8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_11_4                            = UnitField.UNIT_END + 0x35,    // 0x0C9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_12_1                            = UnitField.UNIT_END + 0x36,    // 0x0CA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_12_2                            = UnitField.UNIT_END + 0x37,    // 0x0CB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_12_3                            = UnitField.UNIT_END + 0x38,    // 0x0CC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_12_4                            = UnitField.UNIT_END + 0x39,    // 0x0CD - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_13_1                            = UnitField.UNIT_END + 0x3A,    // 0x0CE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_13_2                            = UnitField.UNIT_END + 0x3B,    // 0x0CF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_13_3                            = UnitField.UNIT_END + 0x3C,    // 0x0D0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_13_4                            = UnitField.UNIT_END + 0x3D,    // 0x0D1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_14_1                            = UnitField.UNIT_END + 0x3E,    // 0x0D2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_14_2                            = UnitField.UNIT_END + 0x3F,    // 0x0D3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_14_3                            = UnitField.UNIT_END + 0x40,    // 0x0D4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_14_4                            = UnitField.UNIT_END + 0x41,    // 0x0D5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_15_1                            = UnitField.UNIT_END + 0x42,    // 0x0D6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_15_2                            = UnitField.UNIT_END + 0x43,    // 0x0D7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_15_3                            = UnitField.UNIT_END + 0x44,    // 0x0D8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_15_4                            = UnitField.UNIT_END + 0x45,    // 0x0D9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_16_1                            = UnitField.UNIT_END + 0x46,    // 0x0DA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_16_2                            = UnitField.UNIT_END + 0x47,    // 0x0DB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_16_3                            = UnitField.UNIT_END + 0x48,    // 0x0DC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_16_4                            = UnitField.UNIT_END + 0x49,    // 0x0DD - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_17_1                            = UnitField.UNIT_END + 0x4A,    // 0x0DE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_17_2                            = UnitField.UNIT_END + 0x4B,    // 0x0DF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_17_3                            = UnitField.UNIT_END + 0x4C,    // 0x0E0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_17_4                            = UnitField.UNIT_END + 0x4D,    // 0x0E1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_18_1                            = UnitField.UNIT_END + 0x4E,    // 0x0E2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_18_2                            = UnitField.UNIT_END + 0x4F,    // 0x0E3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_18_3                            = UnitField.UNIT_END + 0x50,    // 0x0E4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_18_4                            = UnitField.UNIT_END + 0x51,    // 0x0E5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_19_1                            = UnitField.UNIT_END + 0x52,    // 0x0E6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_19_2                            = UnitField.UNIT_END + 0x53,    // 0x0E7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_19_3                            = UnitField.UNIT_END + 0x54,    // 0x0E8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_19_4                            = UnitField.UNIT_END + 0x55,    // 0x0E9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_20_1                            = UnitField.UNIT_END + 0x56,    // 0x0EA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_20_2                            = UnitField.UNIT_END + 0x57,    // 0x0EB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_20_3                            = UnitField.UNIT_END + 0x58,    // 0x0EC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_20_4                            = UnitField.UNIT_END + 0x59,    // 0x0ED - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_21_1                            = UnitField.UNIT_END + 0x5A,    // 0x0EE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_21_2                            = UnitField.UNIT_END + 0x5B,    // 0x0EF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_21_3                            = UnitField.UNIT_END + 0x5C,    // 0x0F0 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_21_4                            = UnitField.UNIT_END + 0x5D,    // 0x0F1 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_22_1                            = UnitField.UNIT_END + 0x5E,    // 0x0F2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_22_2                            = UnitField.UNIT_END + 0x5F,    // 0x0F3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_22_3                            = UnitField.UNIT_END + 0x60,    // 0x0F4 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_22_4                            = UnitField.UNIT_END + 0x61,    // 0x0F5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_23_1                            = UnitField.UNIT_END + 0x62,    // 0x0F6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_23_2                            = UnitField.UNIT_END + 0x63,    // 0x0F7 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_23_3                            = UnitField.UNIT_END + 0x64,    // 0x0F8 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_23_4                            = UnitField.UNIT_END + 0x65,    // 0x0F9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_24_1                            = UnitField.UNIT_END + 0x66,    // 0x0FA - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_24_2                            = UnitField.UNIT_END + 0x67,    // 0x0FB - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_24_3                            = UnitField.UNIT_END + 0x68,    // 0x0FC - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_24_4                            = UnitField.UNIT_END + 0x69,    // 0x0FD - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_25_1                            = UnitField.UNIT_END + 0x6A,    // 0x0FE - Size: 1 - Type: INT - Flags: GROUP_ONLY
        PLAYER_QUEST_LOG_25_2                            = UnitField.UNIT_END + 0x6B,    // 0x0FF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_QUEST_LOG_25_3                            = UnitField.UNIT_END + 0x6C,    // 0x100 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_QUEST_LOG_25_4                            = UnitField.UNIT_END + 0x6D,    // 0x101 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_VISIBLE_ITEM_1_ENTRYID                    = UnitField.UNIT_END + 0x6E,    // 0x102 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_1_ENCHANTMENT                = UnitField.UNIT_END + 0x6F,    // 0x103 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_2_ENTRYID                    = UnitField.UNIT_END + 0x70,    // 0x104 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_2_ENCHANTMENT                = UnitField.UNIT_END + 0x71,    // 0x105 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_3_ENTRYID                    = UnitField.UNIT_END + 0x72,    // 0x106 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_3_ENCHANTMENT                = UnitField.UNIT_END + 0x73,    // 0x107 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_4_ENTRYID                    = UnitField.UNIT_END + 0x74,    // 0x108 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_4_ENCHANTMENT                = UnitField.UNIT_END + 0x75,    // 0x109 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_5_ENTRYID                    = UnitField.UNIT_END + 0x76,    // 0x10A - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_5_ENCHANTMENT                = UnitField.UNIT_END + 0x77,    // 0x10B - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_6_ENTRYID                    = UnitField.UNIT_END + 0x78,    // 0x10C - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_6_ENCHANTMENT                = UnitField.UNIT_END + 0x79,    // 0x10D - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_7_ENTRYID                    = UnitField.UNIT_END + 0x7A,    // 0x10E - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_7_ENCHANTMENT                = UnitField.UNIT_END + 0x7B,    // 0x10F - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_8_ENTRYID                    = UnitField.UNIT_END + 0x7C,    // 0x110 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_8_ENCHANTMENT                = UnitField.UNIT_END + 0x7D,    // 0x111 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_9_ENTRYID                    = UnitField.UNIT_END + 0x7E,    // 0x112 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_9_ENCHANTMENT                = UnitField.UNIT_END + 0x7F,    // 0x113 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_10_ENTRYID                   = UnitField.UNIT_END + 0x80,    // 0x114 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_10_ENCHANTMENT               = UnitField.UNIT_END + 0x81,    // 0x115 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_11_ENTRYID                   = UnitField.UNIT_END + 0x82,    // 0x116 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_11_ENCHANTMENT               = UnitField.UNIT_END + 0x83,    // 0x117 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_12_ENTRYID                   = UnitField.UNIT_END + 0x84,    // 0x118 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_12_ENCHANTMENT               = UnitField.UNIT_END + 0x85,    // 0x119 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_13_ENTRYID                   = UnitField.UNIT_END + 0x86,    // 0x11A - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_13_ENCHANTMENT               = UnitField.UNIT_END + 0x87,    // 0x11B - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_14_ENTRYID                   = UnitField.UNIT_END + 0x88,    // 0x11C - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_14_ENCHANTMENT               = UnitField.UNIT_END + 0x89,    // 0x11D - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_15_ENTRYID                   = UnitField.UNIT_END + 0x8A,    // 0x11E - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_15_ENCHANTMENT               = UnitField.UNIT_END + 0x8B,    // 0x11F - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_16_ENTRYID                   = UnitField.UNIT_END + 0x8C,    // 0x120 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_16_ENCHANTMENT               = UnitField.UNIT_END + 0x8D,    // 0x121 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_17_ENTRYID                   = UnitField.UNIT_END + 0x8E,    // 0x122 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_17_ENCHANTMENT               = UnitField.UNIT_END + 0x8F,    // 0x123 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_18_ENTRYID                   = UnitField.UNIT_END + 0x90,    // 0x124 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_18_ENCHANTMENT               = UnitField.UNIT_END + 0x91,    // 0x125 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_19_ENTRYID                   = UnitField.UNIT_END + 0x92,    // 0x126 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_19_ENCHANTMENT               = UnitField.UNIT_END + 0x93,    // 0x127 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
        PLAYER_CHOSEN_TITLE                              = UnitField.UNIT_END + 0x94,    // 0x128 - Size: 1 - Type: INT - Flags: PUBLIC
        PLAYER_FIELD_PAD_0                               = UnitField.UNIT_END + 0x95,    // 0x129 - Size: 1 - Type: INT - Flags: NONE
        PLAYER_FIELD_INV_SLOT_HEAD                       = UnitField.UNIT_END + 0x96,    // 0x12A - Size: 46 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_PACK_SLOT_1                         = UnitField.UNIT_END + 0xC4,    // 0x158 - Size: 32 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_BANK_SLOT_1                         = UnitField.UNIT_END + 0xE4,    // 0x178 - Size: 56 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_BANKBAG_SLOT_1                      = UnitField.UNIT_END + 0x11C,   // 0x1B0 - Size: 14 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1                = UnitField.UNIT_END + 0x12A,   // 0x1BE - Size: 24 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_KEYRING_SLOT_1                      = UnitField.UNIT_END + 0x142,   // 0x1D6 - Size: 64 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1                = UnitField.UNIT_END + 0x182,   // 0x216 - Size: 64 - Type: GUID - Flags: PRIVATE
        PLAYER_FARSIGHT                                  = UnitField.UNIT_END + 0x1C2,   // 0x256 - Size: 2 - Type: GUID - Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES                       = UnitField.UNIT_END + 0x1C4,   // 0x258 - Size: 2 - Type: GUID - Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES1                      = UnitField.UNIT_END + 0x1C6,   // 0x25A - Size: 2 - Type: GUID - Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES2                      = UnitField.UNIT_END + 0x1C8,   // 0x25C - Size: 2 - Type: GUID - Flags: PRIVATE
        PLAYER_FIELD_KNOWN_CURRENCIES                    = UnitField.UNIT_END + 0x1CA,   // 0x25E - Size: 2 - Type: GUID - Flags: PRIVATE
        PLAYER_XP                                        = UnitField.UNIT_END + 0x1CC,   // 0x260 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_NEXT_LEVEL_XP                             = UnitField.UNIT_END + 0x1CD,   // 0x261 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_SKILL_INFO_1_1                            = UnitField.UNIT_END + 0x1CE,   // 0x262 - Size: 384 - Type: TWO_SHORT - Flags: PRIVATE
        PLAYER_CHARACTER_POINTS1                         = UnitField.UNIT_END + 0x34E,   // 0x3E2 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_CHARACTER_POINTS2                         = UnitField.UNIT_END + 0x34F,   // 0x3E3 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_TRACK_CREATURES                           = UnitField.UNIT_END + 0x350,   // 0x3E4 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_TRACK_RESOURCES                           = UnitField.UNIT_END + 0x351,   // 0x3E5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_BLOCK_PERCENTAGE                          = UnitField.UNIT_END + 0x352,   // 0x3E6 - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_DODGE_PERCENTAGE                          = UnitField.UNIT_END + 0x353,   // 0x3E7 - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_PARRY_PERCENTAGE                          = UnitField.UNIT_END + 0x354,   // 0x3E8 - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_EXPERTISE                                 = UnitField.UNIT_END + 0x355,   // 0x3E9 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_OFFHAND_EXPERTISE                         = UnitField.UNIT_END + 0x356,   // 0x3EA - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_CRIT_PERCENTAGE                           = UnitField.UNIT_END + 0x357,   // 0x3EB - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_RANGED_CRIT_PERCENTAGE                    = UnitField.UNIT_END + 0x358,   // 0x3EC - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_OFFHAND_CRIT_PERCENTAGE                   = UnitField.UNIT_END + 0x359,   // 0x3ED - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_SPELL_CRIT_PERCENTAGE1                    = UnitField.UNIT_END + 0x35A,   // 0x3EE - Size: 7 - Type: FLOAT - Flags: PRIVATE
        PLAYER_SHIELD_BLOCK                              = UnitField.UNIT_END + 0x361,   // 0x3F5 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE              = UnitField.UNIT_END + 0x362,   // 0x3F6 - Size: 1 - Type: FLOAT - Flags: PRIVATE
        PLAYER_EXPLORED_ZONES_1                          = UnitField.UNIT_END + 0x363,   // 0x3F7 - Size: 128 - Type: BYTES - Flags: PRIVATE
        PLAYER_REST_STATE_EXPERIENCE                     = UnitField.UNIT_END + 0x3E3,   // 0x477 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_COINAGE                             = UnitField.UNIT_END + 0x3E4,   // 0x478 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_POS                 = UnitField.UNIT_END + 0x3E5,   // 0x479 - Size: 7 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_NEG                 = UnitField.UNIT_END + 0x3EC,   // 0x480 - Size: 7 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT                 = UnitField.UNIT_END + 0x3F3,   // 0x487 - Size: 7 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_HEALING_DONE_POS                = UnitField.UNIT_END + 0x3FA,   // 0x48E - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_TARGET_RESISTANCE               = UnitField.UNIT_END + 0x3FB,   // 0x48F - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE      = UnitField.UNIT_END + 0x3FC,   // 0x490 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_BYTES                               = UnitField.UNIT_END + 0x3FD,   // 0x491 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_AMMO_ID                                   = UnitField.UNIT_END + 0x3FE,   // 0x492 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_SELF_RES_SPELL                            = UnitField.UNIT_END + 0x3FF,   // 0x493 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_PVP_MEDALS                          = UnitField.UNIT_END + 0x400,   // 0x494 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_BUYBACK_PRICE_1                     = UnitField.UNIT_END + 0x401,   // 0x495 - Size: 12 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1                 = UnitField.UNIT_END + 0x40D,   // 0x4A1 - Size: 12 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_KILLS                               = UnitField.UNIT_END + 0x419,   // 0x4AD - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
        PLAYER_FIELD_TODAY_CONTRIBUTION                  = UnitField.UNIT_END + 0x41A,   // 0x4AE - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_YESTERDAY_CONTRIBUTION              = UnitField.UNIT_END + 0x41B,   // 0x4AF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_LIFETIME_HONORBALE_KILLS            = UnitField.UNIT_END + 0x41C,   // 0x4B0 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_BYTES2                              = UnitField.UNIT_END + 0x41D,   // 0x4B1 - Size: 1 - Type: BYTES - Flags: PRIVATE
        PLAYER_FIELD_WATCHED_FACTION_INDEX               = UnitField.UNIT_END + 0x41E,   // 0x4B2 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_COMBAT_RATING_1                     = UnitField.UNIT_END + 0x41F,   // 0x4B3 - Size: 25 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1                 = UnitField.UNIT_END + 0x438,   // 0x4CC - Size: 18 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_HONOR_CURRENCY                      = UnitField.UNIT_END + 0x44A,   // 0x4DE - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_ARENA_CURRENCY                      = UnitField.UNIT_END + 0x44B,   // 0x4DF - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_MAX_LEVEL                           = UnitField.UNIT_END + 0x44C,   // 0x4E0 - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_DAILY_QUESTS_1                      = UnitField.UNIT_END + 0x44D,   // 0x4E1 - Size: 25 - Type: INT - Flags: PRIVATE
        PLAYER_RUNE_REGEN_1                              = UnitField.UNIT_END + 0x466,   // 0x4FA - Size: 4 - Type: FLOAT - Flags: PRIVATE
        PLAYER_NO_REAGENT_COST_1                         = UnitField.UNIT_END + 0x46A,   // 0x4FE - Size: 3 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_GLYPH_SLOTS_1                       = UnitField.UNIT_END + 0x46D,   // 0x501 - Size: 6 - Type: INT - Flags: PRIVATE
        PLAYER_FIELD_GLYPHS_1                            = UnitField.UNIT_END + 0x473,   // 0x507 - Size: 6 - Type: INT - Flags: PRIVATE
        PLAYER_GLYPHS_ENABLED                            = UnitField.UNIT_END + 0x479,   // 0x50D - Size: 1 - Type: INT - Flags: PRIVATE
        PLAYER_END                                       = UnitField.UNIT_END + 0x47A    // 0x50E
    }

    public enum GameObjectField
    {
        GAMEOBJECT_FIELD_CREATED_BY                      = ObjectField.OBJECT_END + 0x0,   // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
        GAMEOBJECT_DISPLAYID                             = ObjectField.OBJECT_END + 0x2,   // 0x008 - Size: 1 - Type: INT - Flags: PUBLIC
        GAMEOBJECT_FLAGS                                 = ObjectField.OBJECT_END + 0x3,   // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
        GAMEOBJECT_PARENTROTATION                        = ObjectField.OBJECT_END + 0x4,   // 0x00A - Size: 4 - Type: FLOAT - Flags: PUBLIC
        GAMEOBJECT_DYNAMIC                               = ObjectField.OBJECT_END + 0x8,   // 0x00E - Size: 1 - Type: BYTES - Flags: DYNAMIC
        GAMEOBJECT_FACTION                               = ObjectField.OBJECT_END + 0x9,   // 0x00F - Size: 1 - Type: INT - Flags: PUBLIC
        GAMEOBJECT_LEVEL                                 = ObjectField.OBJECT_END + 0xA,   // 0x010 - Size: 1 - Type: INT - Flags: PUBLIC
        GAMEOBJECT_BYTES_1                               = ObjectField.OBJECT_END + 0xB,   // 0x011 - Size: 1 - Type: BYTES - Flags: PUBLIC
        GAMEOBJECT_END                                   = ObjectField.OBJECT_END + 0xC    // 0x012
    }

    public enum DynamicObjectField
    {
        DYNAMICOBJECT_CASTER                             = ObjectField.OBJECT_END + 0x0,   // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
        DYNAMICOBJECT_BYTES                              = ObjectField.OBJECT_END + 0x2,   // 0x008 - Size: 1 - Type: BYTES - Flags: PUBLIC
        DYNAMICOBJECT_SPELLID                            = ObjectField.OBJECT_END + 0x3,   // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
        DYNAMICOBJECT_RADIUS                             = ObjectField.OBJECT_END + 0x4,   // 0x00A - Size: 1 - Type: FLOAT - Flags: PUBLIC
        DYNAMICOBJECT_POS_X                              = ObjectField.OBJECT_END + 0x5,   // 0x00B - Size: 1 - Type: FLOAT - Flags: PUBLIC
        DYNAMICOBJECT_POS_Y                              = ObjectField.OBJECT_END + 0x6,   // 0x00C - Size: 1 - Type: FLOAT - Flags: PUBLIC
        DYNAMICOBJECT_POS_Z                              = ObjectField.OBJECT_END + 0x7,   // 0x00D - Size: 1 - Type: FLOAT - Flags: PUBLIC
        DYNAMICOBJECT_FACING                             = ObjectField.OBJECT_END + 0x8,   // 0x00E - Size: 1 - Type: FLOAT - Flags: PUBLIC
        DYNAMICOBJECT_CASTTIME                           = ObjectField.OBJECT_END + 0x9,   // 0x00F - Size: 1 - Type: INT - Flags: PUBLIC
        DYNAMICOBJECT_END                                = ObjectField.OBJECT_END + 0xA    // 0x010
    }

    public enum CorpseField
    {
        CORPSE_FIELD_OWNER                               = ObjectField.OBJECT_END + 0x0,   // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
        CORPSE_FIELD_PARTY                               = ObjectField.OBJECT_END + 0x2,   // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
        CORPSE_FIELD_DISPLAY_ID                          = ObjectField.OBJECT_END + 0x4,   // 0x00A - Size: 1 - Type: INT - Flags: PUBLIC
        CORPSE_FIELD_ITEM                                = ObjectField.OBJECT_END + 0x5,   // 0x00B - Size: 19 - Type: INT - Flags: PUBLIC
        CORPSE_FIELD_BYTES_1                             = ObjectField.OBJECT_END + 0x18,  // 0x01E - Size: 1 - Type: BYTES - Flags: PUBLIC
        CORPSE_FIELD_BYTES_2                             = ObjectField.OBJECT_END + 0x19,  // 0x01F - Size: 1 - Type: BYTES - Flags: PUBLIC
        CORPSE_FIELD_GUILD                               = ObjectField.OBJECT_END + 0x1A,  // 0x020 - Size: 1 - Type: INT - Flags: PUBLIC
        CORPSE_FIELD_FLAGS                               = ObjectField.OBJECT_END + 0x1B,  // 0x021 - Size: 1 - Type: INT - Flags: PUBLIC
        CORPSE_FIELD_DYNAMIC_FLAGS                       = ObjectField.OBJECT_END + 0x1C,  // 0x022 - Size: 1 - Type: INT - Flags: DYNAMIC
        CORPSE_FIELD_PAD                                 = ObjectField.OBJECT_END + 0x1D,  // 0x023 - Size: 1 - Type: INT - Flags: NONE
        CORPSE_END                                       = ObjectField.OBJECT_END + 0x1E   // 0x024
    }
}
